# Generated by Django 5.2.10 on 2026-02-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_height_customuser_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('advisor', 'Conseiller')], default='client', max_length=10),
        ),
    ]
