# Generated by Django 5.2.10 on 2026-02-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customuser_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='smoker',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
