# Generated by Django 5.2.10 on 2026-02-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_customuser_smoker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='region',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
